org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.warning.mode=all

modId=oc2r
neo_version=21.1.248
minecraft_version=1.21.1
minecraft_sdk=neoforge

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

semver=0.1.1

curse_project_id=1037738
modrinth_project_id=F1gm4RsH

ceres_version=0.0.6
sedna_version=2.0.13
sedna_buildroot_version=0.0.70
network_lib_version=1.0.4
jei_version=19.44.0.403
native_networking_repo=North-Western-Development/oc2r-native-networking

apache_commons_version=4.4
markdownmanual_project_id=1412825
markdownmanual_file_id=7374817
architectury_project_id=419699
architectury_file_id=5786327

pr_version=4.23.0
ccl_version=4.6.1.+
cbm_version=3.5.0.+

debug_embeddium=false
debug_embeddium_plus_plus=false
debug_oculus=false

embeddium_project_id=908741
embeddium_file_id=5521846
embeddium_plus_plus_project_id=931925
embeddium_plus_plus_file_id=5436746
oculus_project_id=581495
oculus_file_id=5299671

mockito_version=5.23.0
jupiter_version=5.13.4
